// Generated by Wrangler by running `wrangler types`

interface Env {
  SAMUI_HONO_CF_WORKERS_KV: KVNamespace
  SOLANA_RPC_URL: 'https://api.devnet.solana.com'
  BETTER_AUTH_SECRET: string
  BETTER_AUTH_URL: string
  DATABASE_URL: string
  SIGNER_SECRET_KEY: string
}
