// Generated by Wrangler by running `wrangler types`

interface Env {
	SAMUI_HONO_CF_WORKERS_KV: KVNamespace;
	SOLANA_RPC_URL: "https://api.devnet.solana.com";
	SOLANA_RPC_URL_SUBSCRIPTIONS: "";
	SIGNER_SECRET_KEY: string;
}
