name = "samui-hono-cf-workers"
main = "src/index.ts"
compatibility_date = "2024-12-23"
compatibility_flags = ["nodejs_compat_v2"]
keep_vars = true

[vars]
SOLANA_RPC_URL = "https://api.devnet.solana.com"

[[kv_namespaces]]
binding = "SAMUI_HONO_CF_WORKERS_KV"
id = "6e6599552be54693985312d3c77dd580"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability.logs]
enabled = true
# head_sampling_rate = 1